service: sls-postgresql-example

plugins:
  - serverless-aws-lambda

package:
  individually: true
  files:
    - { at: .aws_lambda/bundled_node_modules/, as: node_modules }

custom:
  timeout: 10
  serverless-aws-lambda:
    configPath: ./slsconfig.ts

  local:
    DB_HOST: localhost:5432
    DB_NAME: myDb
    DB_USER: postgres
    DB_PASSWORD: 5678

  prod:
    DB_HOST: prodhost:5432
    DB_NAME: myProdDb
    DB_USER: produser
    DB_PASSWORD: prodsecret

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  timeout: ${self:custom.timeout}
  versionFunctions: false
  deploymentMethod: direct

  environment:
    TIMEOUT: ${self:custom.timeout}
    DB_HOST: ${self:custom.${opt:stage, 'local'}.DB_HOST}
    DB_NAME: ${self:custom.${opt:stage, 'local'}.DB_NAME}
    DB_USER: ${self:custom.${opt:stage, 'local'}.DB_USER}
    DB_PASSWORD: ${self:custom.${opt:stage, 'local'}.DB_PASSWORD}

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3001
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: true

functions:
  # Manager APIs
  createManager:
    handler: src/handlers/createManager.default
    events:
      - httpApi:
          method: POST
          path: /managers

  getManager:
    handler: src/handlers/getManager.default
    events:
      - httpApi:
          method: GET
          path: /managers/{cognitoId}

  # Tenant APIs
  createTenant:
    handler: src/handlers/createTenant.default
    events:
      - httpApi:
          method: POST
          path: /tenants

  getTenant:
    handler: src/handlers/getTenant.default
    events:
      - httpApi:
          method: GET
          path: /tenants/{cognitoId}
